DATABASE:
  HOST: ${DATABASE_HOST}
  PORT: ${DATABASE_PORT}
  NAME: ${DATABASE_NAME}
  USERNAME: ${DATABASE_USERNAME}
  PASSWORD: ${DATABASE_PASSWORD}

AWS:
  S3:
    BUCKET: ${AWS_S3_BUCKET}
    ACCESS-KEY: ${AWS_S3_ACCESS-KEY}
    SECRET-KEY: ${AWS_S3_SECRET-KEY}
